Algoritmo "semnome"

Var
   A1,A2, w1,w2,w3,w4,w:real

Inicio
    escreva("Digite um valor?:")
    leia(A1)
    escreva("Digite o proximo valor?:")
    leia(A2)
    w1<-A1+A2
    W2<-A1*A2
    W3<-A1-A2
    w4<-A1/A2
    escreval("A soma é igual á:",w1:3:2)
    escreval("A Multiplicação é igual á:",w2:3:2)
    escreval("A subtraçao é igual á:",w3:3:2)
    escreval("A divisão é igual á:",w4:3:2)
Fimalgoritmo